/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.samplejavafx;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertTrue(true);
    }
}
