/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.samplejavafx;

public class App {
    public static void main(String[] args) {
        JavaFXApp2.main(args);
    }
}
